version: '3.8'

services:
  db:
    image: mysql:8
    container_name: ebookhub_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ebookhub_store_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
